datasource:
  postgresql:
    #url: postgres://ysvgldxcexzbid:bfmSjlPqHbBqW2mrDHrZ-NsRek@ec2-23-21-166-16.compute-1.amazonaws.com:5432/dc4tst5151mkib
    url:  jdbc:postgresql://ec2-23-21-166-16.compute-1.amazonaws.com:5432/dc4tst5151mkib?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: ysvgldxcexzbid
    password: bfmSjlPqHbBqW2mrDHrZ-NsRek
    driver-class-name: org.postgresql.Driver
    validation-query: select 1
#  openedge:  
#    url: jdbc:datadirect:openedge://c217u083.cg.na.jci.com:12700;DatabaseName=symix
 #   username: E2Open
  #  password: nepO2E01
   # driver-class-name: com.ddtek.jdbc.openedge.OpenEdgeDriver
    #validation-query: select 1
    
  #mysql:
    #url: jdbc:mysql://localhost:3306/primary
    #username: root
    #password: root
    #driver-class-name: com.mysql.jdbc.Driver
    #validation-query: select 1
    
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
security:
  user:
    password: ${eureka.password}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
  
  
logging:
  level:
    org.springframework: INFO
    com.jci: DEBUG
    com.liquibase: DEBUG
    
