datasource:
  postgresql:
    #url: postgres://ysvgldxcexzbid:bfmSjlPqHbBqW2mrDHrZ-NsRek@ec2-23-21-166-16.compute-1.amazonaws.com:5432/dc4tst5151mkib
    #url:  jdbc:postgresql://ec2-23-21-166-16.compute-1.amazonaws.com:5432/dc4tst5151mkib?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    #username: ysvgldxcexzbid
    #password: bfmSjlPqHbBqW2mrDHrZ-NsRek
    #driver-class-name: org.postgresql.Driver
    #validation-query: select 1
    url:  jdbc:postgresql://ec2-54-163-225-208.compute-1.amazonaws.com:5432/d49qqikmptome3?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: ykdsdlwjqzmski
    password: chQKB0H11dSFjmLPY7thf0K9Pf
    driver-class-name: org.postgresql.Driver
    validation-query: select 1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  user:
    password: ${eureka.password}

---
spring:
  profiles: heroku
#eureka:
 # instance:
  #  hostname: ${DOMAIN_NAME}
   # nonSecurePort: 80
  #password: ${USER_PASSWORD:password}
  
    
