datasource:
  postgresql:
    #url: postgres://ysvgldxcexzbid:bfmSjlPqHbBqW2mrDHrZ-NsRek@ec2-23-21-166-16.compute-1.amazonaws.com:5432/dc4tst5151mkib
    #url:  jdbc:postgresql://ec2-23-21-166-16.compute-1.amazonaws.com:5432/dc4tst5151mkib?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    #username: ysvgldxcexzbid
    #password: bfmSjlPqHbBqW2mrDHrZ-NsRek
    #driver-class-name: org.postgresql.Driver
    #validation-query: select 1
    
    url:  jdbc:postgresql://ec2-54-243-226-163.compute-1.amazonaws.com:5432/d2foonjeq1t111?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: jwqjeqduomkzhr
    password: dFjlD87qurE3PjJBExUwQDubY-
    driver-class-name: org.postgresql.Driver
    validation-query: select 1

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/
security:
  user:
    password: ${eureka.password}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
  
    
